version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    ignore:
      - dependency-name: "@types/*"
      - dependency-name: "eslint"
      - dependency-name: "eslint-*"
      - dependency-name: "typescript"
      - dependency-name: "jest"
      - dependency-name: "jest-*"
    versioning-strategy: 'increase'
    commit-message:
      prefix: "chore(deps): "

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(deps): "
