version: v1

labels:
  ### Actually using for workflow
  - label: "feat"
    matcher:
      title: "^feat:.*"
      branch: "^feat/.*"
      commits: "^feat:.*"

  - label: "fix"
    matcher:
      title: "^fix:.*"
      branch: "^fix/.*"
      commits: "^fix:.*"

  - label: "chore"
    matcher:
      title: "^chore(\\((deps|ci)\\))?:.*"
      branch: "^chore/.*"
      commits: "^chore(\\((deps|ci)\\))?:.*"

  - label: "docs"
    matcher:
      title: "^docs:.*"
      branch: "^docs/.*"
      commits: "^docs:.*"

  - label: "test:labeler"
    matcher:
      files: ".github/labeler.yml"

  - label: "test:dist"
    matcher:
      files: ["dist/*"]

  - label: "test:tests"
    matcher:
      files: [ "__tests__/matcher/**", "__tests__/*.ts" ]

  - label: "test:body"
    matcher:
      body: "(\\n|.)*- \\[x\\] test(\\n|.)*"

  - label: "test:comment"
    matcher:
      comment: "# \\[Codecov\\] .*"

  - label: "test:stale"
    matcher:
      comment: "/stale"
