version: v1

labels:
  ### Actually using for workflow
  - label: "feat"
    matcher:
      title: "^feat:.*"
      branch: "^feat/.*"
      commits: "^feat:.*"

  - label: "fix"
    matcher:
      title: "^fix:.*"
      branch: "^fix/.*"
      commits: "^fix:.*"

  - label: "chore"
    matcher:
      title: "^chore(\\((deps|ci)\\))?:.*"
      branch: "^chore/.*"
      commits: "^chore(\\((deps|ci)\\))?:.*"

  - label: "docs"
    matcher:
      title: "^docs:.*"
      branch: "^docs/.*"
      commits: "^docs:.*"

  ### Examples
  - label: "test:dist"
    matcher:
      files: "dist/**"

  - label: "test:security"
    matcher:
      files: [ ".github/**", "security/**" ]

  - label: "test:body"
    matcher:
      body: "(\\n|.)*- \\[x\\] test(\\n|.)*"

  - label: "test:comments"
    matcher:
      comments: "# \\[Codecov\\] .*"


