name: 'Multi Labeler'
description: 'Multi labeler for title, body, comments, commit messages, branch or files.'
author: 'Fuxing Loh'
branding:
  icon: tag
  color: yellow

inputs:
  github-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  config-path:
    description: 'The path for the label configurations'
    default: '.github/labeler.yml'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
