name: CI Package

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    environment: fuxingloh/multi-labeler workflow
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: '.nvmrc'

      - run: npm install
      - run: npm run build
      - run: npm run package

      - id: app
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.WORKFLOW_APP_ID }}
          private_key: ${{ secrets.WORKFLOW_PRIVATE_KEY }}

      - uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6.1.0
        with:
          token: ${{ steps.app.outputs.token }}
          commit-message: 'chore(ci): npm run package'
          title: 'chore(ci): npm run package'
          body: |
            #### What this PR does / why we need it:

            Updated `./dist/**` files with `npm run package`.

          branch: ci-package
