name: CI

on:
  pull_request:
  issues:
  issue_comment:

jobs:
  uses:
    name: Uses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
