name: CI

on:
  pull_request:
    types: [ opened, reopened, edited, synchronize, ready_for_review, labeled, unlabeled ]
  issues:
  issue_comment:

permissions:
  contents: read
  issues: write
  pull-requests: write
  statuses: write

jobs:
  uses:
    name: Uses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - uses: ./
