name: CI

on:
  pull_request:
    types: [ opened, reopened, edited, synchronize, ready_for_review, labeled, unlabeled ]
  issues:
  issue_comment:

jobs:
  uses:
    name: Uses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v3
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `<details><summary>Debug Payload Information</summary>\n\n\`\`\`json\n${JSON.stringify(context, undefined, 2)}\n\`\`\`\n\n</details>`
            })
      - uses: ./
