name: CI Use

on:
  pull_request:
    types: [opened, reopened, edited, synchronize, ready_for_review, labeled, unlabeled]
  issues:
  issue_comment:

permissions:
  contents: read
  issues: write
  pull-requests: write
  statuses: write

jobs:
  action:
    name: Multi Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: ./
