name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - run: npm install
      - run: npm run ci

      - uses: EndBug/add-and-commit@d4d066316a2a85974a05efb42be78f897793c6d9
        with:
          add: 'dist'
          message: 'npm run ncc, dist updated'
