name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm install
      - run: npm run ci

      - uses: EndBug/add-and-commit@756d9ea820f11931e591eaf57f25e0f5b903d5b2
        with:
          add: 'dist'
          message: 'npm run ncc, dist updated'
