name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - run: npm install
      - run: npm run ci

      - uses: EndBug/add-and-commit@8bd0710add0b23d6700a988d5754629ea03714ef # tag=v9.1.0
        with:
          add: 'dist'
          message: 'npm run ncc, dist updated'
