name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm install
      - run: npm run ci

      - uses: EndBug/add-and-commit@b3c7c1e078a023d75fb0bd326e02962575ce0519
        with:
          add: 'dist'
          message: 'npm run ncc, dist updated'
